package pl.kenbit.maps.icao;

import java.awt.Dimension;
import java.awt.Image;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class Icao extends javax.swing.JFrame {

    Data data;
    
    public Icao() {
    	setAlwaysOnTop(true);
//    	setVisible(true);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNewLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                swapInRunTime();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                swapInRunTime();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                swapInRunTime();
            }
        });
        
        setTitle("ICAO Code Generator");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Wygenerowany kod");

        jLabel1.setText("Wpisz kod do wygenerowania");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        
        lblNewLabel.setText("");
        Image img= new ImageIcon(this.getClass().getResource("icao.png")).getImage();
        Image newImg = img.getScaledInstance(100, 80, java.awt.Image.SCALE_SMOOTH);
        lblNewLabel.setIcon(new ImageIcon(newImg));
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel2)
        					.addGap(18)
        					.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 388, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel1)
        					.addGap(34)
        					.addComponent(jTextField1)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        			.addGap(28))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(17)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel1)
        						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel2)))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblNewLabel)))
        			.addContainerGap(41, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        
    }

    /**
     * @param args the command line arguments
     */
//    
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNewLabel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
public void swapInRunTime() {
            String generateCode = "";
            jTextField2.setText("");
            String word = jTextField1.getText();
            data = new Data();
            char[] swapStringToArary = word.toCharArray();
            char[] letters = data.letter();
            String[] alphabetICAO = data.alphabetICAO();
            String[] finalWord = new String[word.length()];

            for (int i = 0; i <= swapStringToArary.length - 1; i++) {
                for (int j = 0; j <= letters.length - 1; j++) {
                    if (swapStringToArary[i] == letters[j]) {
                        finalWord[i] = alphabetICAO[j];
                        break;
                    } else {

                    }
                }
            }

            for (int k = 0; k <= finalWord.length - 1; k++) {
                generateCode = generateCode + " - " + finalWord[k];
            }

            if (generateCode.equals("")) {
                jTextField2.setText("");
            } else {
                jTextField2.setText(generateCode + " - ");
            }
        }
}
